@extends('layouts.app-public')

@section('content')

            @include('includes.header')

            <!-- banner start -->
			<!-- ================ -->
			<div class="banner">
				<div class="fixed-image section light-translucent-bg" style="background-image:url('idea/images/about.jpg');">
					<div class="container">
					<div class="space-top"></div>
					<h1>ABOUT US</h1>
					<div class="separator-2"></div>
					<p class="lead">The Local Content Conference is being organised by Marak Alliance LLC in conjunction with international local content experts.<br /> Contact: info@marakconsulting.com</p>
					</div>
				</div>
			</div>
			<!-- banner end -->

			<!-- main-container start -->
			<!-- ================ -->
			<section class="main-container">

				<div class="container">
					<div class="row">

						<!-- main start -->
						<!-- ================ -->
						<div class="main col-md-12">

							<!-- page-title start -->
							<!-- ================ -->
							<h1 class="page-title">BACKGROUND</h1>
							<div class="separator-2"></div>
							<!-- page-title end -->
							
							<div class="row">
								<div class="col-md-12">
									<p>Marak (Inc.) Consulting was established in the UK in 2008 and held its first local content related event on 30 October 2009 in Lagos, Nigeria in conjunction with its Nigerian affiliate, Bellfront Global. This event was partly necessitated by an empirical research conducted by Marak Consulting into the bottlenecks preventing Nigerian companies from participating in the billion-dollar oil/gas supply chain. The event was well attended by delegates including representatives from Chevron; Shell; BG Group; Riise Underwater Engineering; International Energy Services; government representatives from Department of Petroleum Resources (DPR) and National Petroleum Investment Management services (NAPIMS), amongst many others.</p>
									
									<p>Marak (Inc) Consulting have continued to be active in packaging bespoke events, trainings and workshops this past decade, and are currently organizing the current Local Content Conference through the US affiliate, Marak Alliance LLC. Invited speakers and participants have been carefully drawn from a global pool of internationally renowned local content experts from extractive industry, government representatives/policy makers, the World Bank, IMF, OPEC, AU, EU, UN, etc. The confirmed keynote speaker is H.E Goodluck Jonathan, PhD whose regime enacted the Nigerian Oil and Gas Industry Content Development Act 2010 – a game changer for local businesses.</p>

									<p>The Conference is scheduled to hold from 30 April to 02 May 2018 in Houston, Texas during the OTC week to allow delegates attending the OTC to also participate in the event. Extractive industries are central to the economic activities of 81 countries around the world with a combined population of 3.5 billion people. However, despite these resources (oil, gas or minerals), 69% of the population in mostly developing countries live in poverty. Due to lack of local capacity, Multi-National Corporations (MNC) rely on global supply chains to conduct most phases of its business. However, host countries are increasingly demanding localization of the oil/gas supply chains that affords preferential national treatment to indigenous companies through local content policies/laws.</p>

									<p>Local content policies are not a new concept, and its foundation rest on linkage theories and cluster development. The concept is a powerful one since it suggests that through linkages the resource dependent economy will avoid the ‘resource curse”; create more jobs and increase its revenues while diversifying the economy.</p>

									<p>Through local content policies, backward linkages are created when buyers within extractive industries source goods and services for production processes from local suppliers to boost the GDP of the host country. </p>

									<p>Host countries have basically three options for local content policies. One is the adoption of quantitative requirements mandated by legislation where MNC must measure and report a certain percentage of employment or procurement done by locals. The other is a voluntary obligation focusing instead on facilitating or improving the conditions in which local content can prosper, for example by adopting technology transfer or training program. Or a combination of both.</p>

									<p>The enthusiasm for the adoption of local content emerges from the well reported failure of many countries to achieve sustainable economic development out of the revenues and rents generated by the exploitation of their resources. The Conference aims to present the platform for all local content stakeholders (government officials, the oil and gas industry, representatives of the World Bank, IMF, WTO, academia, etc.) to unify efforts to address issues affecting the future of local content, which may be a means of curbing economic migration, conflict between MNCs and host communities as well as extreme poverty in resource rich developing/emerging economies.</p>

									<h2>Answers to the following key questions will be sought at the Conference:</h2>
									<ul class="list-icons">
										<li class="object-non-visible" data-animation-effect="fadeInUpSmall"><i class="icon-check"></i> What challenges and successes flow from the implementation of local content from the perspective of MNCs, National Oil Companies, Oil Servicing Companies and Local Companies?</li>
										<li class="object-non-visible" data-animation-effect="fadeInUpSmall" data-effect-delay="100"><i class="icon-check"></i>How will the World Bank’s decision to stop all lending for oil and gas projects after 2019, with the exception of certain gas projects in the poorest countries facing exceptional circumstances, impact current local content efforts in these nations?</li>
										<li class="object-non-visible" data-animation-effect="fadeInUpSmall" data-effect-delay="300"><i class="icon-check"></i>  How can local content policies help create lateral linkages to achieve UN Sustainable Development Goals and overcome climate change challenges through affordable renewable energy and non-oil dependent economies?</li>
										<li class="object-non-visible" data-animation-effect="fadeInUpSmall" data-effect-delay="500"><i class="icon-check"></i>Would a globally acceptable standard of reporting local content activities by MNCs be preferable to mandatory local content regulations?</li>
										<li class="object-non-visible" data-animation-effect="fadeInUpSmall" data-effect-delay="500"><i class="icon-check"></i>What are the different strategies adopted by MNC’s aimed at increasing local employment and supporting local businesses?</li>
										<li class="object-non-visible" data-animation-effect="fadeInUpSmall" data-effect-delay="500"><i class="icon-check"></i>In regards to extractive corporations, are your local content initiatives confined inside your corporate social responsibility framework, and not always aligned with government industrialization goals or objectives?</li>

									</ul>

									<p>Most of the localization programs have resulted, according to some research, on shallow linkages focusing on low value-added activities.</p>

									<p>It is clear that in recent years a more coordinated effort has emerged, in some climes, between MNC, local business associations, government regulators and international NGO’s, aimed at proposing “best practices” in the implementation of local content policies (voluntarily or legislated). The one-billion-dollar question is: what is the impact so far?</p>
									
									<a class="btn btn-lg btn-default" href="{{asset('/contact')}}"><i class="fa fa-users pr-10"></i> Contact Us</a>
								</div>
								
							</div>
							<hr>
						</div>
						<!-- main end -->

					</div>
				</div>
			</section>
			<!-- main-container end -->

        @include('includes.footer')

        @include('includes.subfooter')
@endsection

